"""empty message

Revision ID: 211cd82c440c
Revises: 
Create Date: 2019-09-01 21:32:25.077577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211cd82c440c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('named_location', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), server_default='US', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kingdom', sa.String(), nullable=True),
    sa.Column('phylum', sa.String(), nullable=True),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('subfamily', sa.String(), nullable=True),
    sa.Column('tribe', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('subgenus', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_date', sa.DateTime(), nullable=True),
    sa.Column('collect_date', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('identified_by', sa.Integer(), nullable=True),
    sa.Column('identified_by_lab', sa.Integer(), nullable=True),
    sa.Column('individual_count', sa.Integer(), nullable=True),
    sa.Column('specimen_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['identified_by'], ['scientist.id'], ),
    sa.ForeignKeyConstraint(['identified_by_lab'], ['laboratory.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_sample')
    op.drop_table('sample')
    op.drop_table('specimen')
    op.drop_table('scientist')
    op.drop_table('location')
    op.drop_table('laboratory')
    # ### end Alembic commands ###
