"""empty message

Revision ID: d0aa9acb2e92
Revises: 39025902cf5d
Create Date: 2019-09-02 11:34:43.062873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0aa9acb2e92'
down_revision = '39025902cf5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'longitude')
    op.drop_column('location', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('location', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
