"""empty message

Revision ID: 20cc53b6e835
Revises: d0aa9acb2e92
Create Date: 2019-09-02 11:39:54.001454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20cc53b6e835'
down_revision = 'd0aa9acb2e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['named_location'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    # ### end Alembic commands ###
