"""empty message

Revision ID: 3b53c9a1c25d
Revises: 1d6038c2ea1f
Create Date: 2019-08-31 16:13:33.358775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b53c9a1c25d'
down_revision = '1d6038c2ea1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specimen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kingdom', sa.String(), nullable=True),
    sa.Column('phylum', sa.String(), nullable=True),
    sa.Column('class', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('subfamily', sa.String(), nullable=True),
    sa.Column('tribe', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('subgenus', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('identified_by', sa.String(), nullable=True),
    sa.Column('identified_by_lab', sa.String(), nullable=True),
    sa.Column('specimen_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_sample')
    op.drop_table('specimen')
    # ### end Alembic commands ###
